r"""LaTeX 编译集成 — 生成 latexmkrc 配置，支持编译前自动插入索引和回滚。

Usage:
    latex-index setup --project-dir .     # 生成 .latexmkrc
    latex-index rollback chapter.tex      # 恢复备份
"""

from __future__ import annotations

import shutil
from datetime import datetime
from pathlib import Path
from typing import List, Optional


def generate_latexmkrc(
    project_dir: str = ".",
    index_config: str = "config/default.yaml",
    backup: bool = True,
) -> str:
    """生成 .latexmkrc 文件内容。

    配置 latexmk 在每次编译前自动运行索引插入，
    并在编译成功后重新运行索引更新。

    Args:
        project_dir: 项目目录
        index_config: 索引配置文件路径
        backup: 是否启用自动备份

    Returns:
        .latexmkrc 文件内容
    """
    lines = [
        "# Auto-generated by latex-index-tool",
        f"# Generated: {datetime.now().isoformat()}",
        "",
        "# ── 索引自动插入 ──",
        "# 在首次编译前插入索引命令到所有章节文件",
        "",
    ]

    if backup:
        lines.extend([
            "# 编译前：备份章节文件",
            'foreach my $ch (1..14) {',
            '  my $fn = sprintf("chapters/Chapter_%d_*.tex", $ch);',
            '  for my $f (glob($fn)) {',
            '    system("cp", $f, "$f.bak");',
            '  }',
            '}',
            "",
        ])

    lines.extend([
        "# 编译前：插入索引",
        "system(",
        '  "latex-index", "insert",',
        '  "--config", "' + index_config + '",',
        '  "--chapter", "1",',
        '  "--dry-run",',  # 安全：默认 preview 模式
        ");",
        "",
        "# 如需自动写入，将上方 --dry-run 移除",
        "",
        "# ── 自定义依赖 ──",
        "# 索引工具变更时触发重新编译",
        "add_cus_dep(\"idx\", \"tex\", 0, \"makeindex\");",
        "",
        "# ── 编译完成后重新生成索引 ──",
        "$makeindex = 'makeindex -s index_style.ist';",
        "$pdflatex = 'xelatex -interaction=nonstopmode -halt-on-error';",
    ])

    return "\n".join(lines)


def generate_arara_rules(project_dir: str = ".") -> str:
    """生成 arara 规则文件内容。

    arara 是另一种流行的 LaTeX 自动化工具。

    Returns:
        arara 规则 YAML 内容
    """
    return """# Auto-generated arara rules for latex-index-tool
!config
identifier: latex-index
name: LaTeXIndexTool
commands:
  - name: Insert index entries
    command: >
      @{
        python -m latex_index insert
        --config config/default.yaml
        --chapter 1
        --dry-run
      }
    exit: 0
authors:
  - latex-index-tool
"""


def create_backup(filepath: str) -> str:
    """创建文件的备份副本。

    Returns:
        备份文件路径
    """
    import time
    src = Path(filepath)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    micro = int(time.perf_counter_ns() % 1000000)
    backup_path = src.with_suffix(f".tex.bak.{timestamp}_{micro:06d}")
    shutil.copy2(str(src), str(backup_path))
    return str(backup_path)


def rollback_file(filepath: str) -> Optional[str]:
    """恢复最近的备份文件。

    Returns:
        恢复到的备份路径，如果没有备份则返回 None
    """
    src = Path(filepath)
    pattern = f"{src.stem}.tex.bak.*"
    backups = sorted(
        src.parent.glob(pattern),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not backups:
        return None
    latest = backups[0]
    shutil.copy2(str(latest), str(src))
    return str(latest)


def list_backups(filepath: str) -> List[str]:
    """列出文件的所有备份。"""
    src = Path(filepath)
    pattern = f"{src.stem}.tex.bak.*"
    return sorted(
        [str(p) for p in src.parent.glob(pattern)],
        reverse=True,
    )


def clean_backups(filepath: str, keep: int = 5) -> int:
    """清理旧备份，仅保留最近 N 个。

    Returns:
        删除的备份数量
    """
    src = Path(filepath)
    pattern = f"{src.stem}.tex.bak.*"
    backups = sorted(
        src.parent.glob(pattern),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    removed = 0
    for old in backups[keep:]:
        old.unlink()
        removed += 1
    return removed
